### ISSUE TITLE
Memory optimization

### ISSUE THREAD

**Issue by IW3IJQ** [tinkerspy/Automaton#28]
Hello!
Maybe nice change the varius "const 'type'.." with "const PROGMEM 'type'.." and use the "F()" statement in trace messages. This to save a fiew byte of RAM.

**Comment by tinkerspy** [comment]
I believe I tried that with trace messages but it turned out to be counterproductive. The way it is now the messages only take up memory when you actually use a trace() call in your sketch (when debugging). When I tried PROGMEM all traces messages were always linked in if only in program memory. So I concluded that the current way is actually better because it makes for more compact production code.
